# Rの基礎

## Rのインストールと使い方

## パッケージのインストール

## Rを使ってみよう
```{r}
#四則演算・累乗の計算
7+8 #足し算
9-4 #引き算
3*8 #掛け算
15/3 #割り算

9^2 #9の2乗
3^3 #3の3乗
4^(1/2) #4の1/2乗　つまり平方根
```

```{r}
#関数を用いた計算
sqrt(9) # 9 の平方根
log(10) # 自然対数 ネイピア数 e(=2.7182…) を底とする対数
log10(100) # 常用対数 10 を底とする対数
log(100, base=10) # 上記と同様
log2(16) # 2 を底とする対数
log(16, base=2) # 上記と同様
exp(1) # e の 1 乗
round(exp(1),3) #数値を丸める
```

## Rにおける変数（オブジェクト）の取り扱い
### スカラーとベクトル
```{r}
x<-2
x

y<-c(1,3,5)
y

(z.0 <- 1:10)

(z.1 <- seq(1,10,1))

(Y <- c(3, 4, 6))

(z1 <- 10:1)

(z.2 <- 2*5)

(students <- c("Aono","Yoshioka","Narihira","Fujiwara","Ueyama"))
```
```{r}
#ベクトル同士の演算
vec.a <- c(1,2,3)
vec.b <- c(2,4,6)
vec.a+vec.b # ベクトルの和
vec.a-vec.b # ベクトルの差
vec.a*vec.b # ベクトルの積
vec.a/vec.b # ベクトルの除算
vec.a%*%vec.b # ベクトルの内積
```

### 行列
```{r}
(mat.a <- matrix(1:8, nrow=4, ncol=2))

(English <- c(59, 65, 74, 42, 25))
(test <- cbind(students, English))
```

### データフレーム
```{r}
(sex <- c("F", "F", "F", "M", "M"))
(Japanese <- c(45, 81, 65, 55, 29))
(test2 <- data.frame(students, sex, English, Japanese))

sum(test2[,3]) # 3 列目が英語の得点
```

### リスト
```{r}
list.a <- list(vec.a, mat.a, students)
list.a

list.a[[1]]
sum(list.a[[1]])
list.a[[2]][1,2] #第2要素(行列)の1行2列
list.a[[2]][1, ] #第2要素(行列)の第1行
list.a[[2]][ ,2] #第2要素(行列)の第2列
list.a[[3]][2] #第3要素(文字列)の第2要素
```